Add gradle android build action

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -3,7 +3,7 @@ on:
     branches: [ "master" ]
 jobs:
   ios-build:
-    name: iOS Dev Build
+    name: iOS Build
     runs-on: macos-latest
     steps:
       - name: Show self-hosted machine infomation
@@ -52,8 +52,60 @@ jobs:
           echo "Found APP_PATH: $APP_PATH"
           echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV
       - name: Upload Build Artifact
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v3.1.3
         with:
           name: ios-build-artifact
           path: ${{ env.APP_PATH }}
+          retention-days: 30
+  android-build:
+    name: Android Build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repo from branch
+        uses: actions/checkout@v3
+
+      - name: Set up JDK 11
+        uses: actions/setup-java@v2
+        with:
+          java-version: '11'
+          distribution: 'adopt'
+
+      - name: Cache Gradle dependencies
+        uses: actions/cache@v2
+        with:
+          path: |
+            ~/.gradle/caches
+            ~/.gradle/wrapper
+          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
+          restore-keys: |
+            ${{ runner.os }}-gradle-
+
+      - name: Install Node.js dependencies
+        run: npm install
+
+      - name: Grant execute permission for Gradle
+        working-directory: android
+        run: chmod +x ./gradlew
+
+      - name: Build with Gradle
+        working-directory: android
+        run: ./gradlew assembleRelease
+
+
+      - name: Find Build Artifact
+        id: find-build
+        run: |
+          APK_PATH=$(find . -name "*.apk" | head -n 1)
+          if [[ -z "$APK_PATH" ]]; then
+            echo "APK file not found"
+            exit 1
+          fi
+          echo "Found APK_PATH: $APK_PATH"
+          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
+
+      - name: Upload Build Artifact
+        uses: actions/upload-artifact@v3.1.3
+        with:
+          name: android-build-artifact
+          path: ${{ env.APK_PATH }}
           retention-days: 30
